// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCabUQfKqXShWpU8OEqXkwE_EMnHcsLoxc',
    appId: '1:102522233118:web:13c6ba843545bc7728690f',
    messagingSenderId: '102522233118',
    projectId: 'hindupoojaapp',
    authDomain: 'hindupoojaapp.firebaseapp.com',
    storageBucket: 'hindupoojaapp.firebasestorage.app',
    measurementId: 'G-FE8DQBE2WS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbIvK19GAvIYWdrTZwGh4ycKHqHDLyvg4',
    appId: '1:102522233118:android:7b3231794a0d726128690f',
    messagingSenderId: '102522233118',
    projectId: 'hindupoojaapp',
    storageBucket: 'hindupoojaapp.firebasestorage.app',
  );

}